build:
   version: "15091992:215245"
accounts:
   message: "Welcome to EazyBank accounts PROD API"
   contactDetails:
      name: "Darcy Mills"
      email: "darcy@mailinator.com"
   onCallSupport:
      - "(022)-10103232"
      - "(022)-90901212"