build:
   version: "18022024:145939"
accounts:
   message: "Welcome to EazyBank accounts local API"
   contactDetails:
      name: "John Doe"
      email: "johndoe@mailinator.com"
   onCallSupport:
      - "(022)-98987676"
      - "(022)-54543232"