build:
   version: "15091992:215245"
accounts:
   message: "Welcome to EazyBank Cards PROD API"
   contactDetails:
      name: "Antoinette Riggs"
      email: "antoinette@mailinator.com"
   onCallSupport:
      - "(022)-10103232"
      - "(022)-90901212"