server:
   port: 8071
   servlet:
      context-path: /configserver
spring:
   application:
      name: "configserver"
   profiles:
      # active: "native"
      active: git
   cloud:
      config:
         server:
            # native:
               # search-locations: "classpath:/config"
               # search-locations: "file:///C://Users//Ninad//Documents//config"
            git:
               uri: "https://gitlab.com/ninadb15/springboot-config.git"
               default-label: main
               timeout: 5
               clone-on-start: true
               force-pull: true

management:
   endpoints:
      web:
         exposure:
            include: "*"
   health:
      readiness-state:
         enabled: true
      liveness-state:
         enabled: true
   endpoint:
      health:
         probes:
            enabled: true